CREATE TABLE IF NOT EXISTS `apikey` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `apikey_no` VARCHAR(255) NOT NULL UNIQUE,
    `key` VARCHAR(255) NOT NULL UNIQUE,
    `status` ENUM('active', 'inactive','revoked') NOT NULL DEFAULT 'active',
    `merchant` VARCHAR(50) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
