// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ApikeyStatus string

const (
	ApikeyStatusActive   ApikeyStatus = "active"
	ApikeyStatusInactive ApikeyStatus = "inactive"
	ApikeyStatusRevoked  ApikeyStatus = "revoked"
)

func (e *ApikeyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApikeyStatus(s)
	case string:
		*e = ApikeyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApikeyStatus: %T", src)
	}
	return nil
}

type NullApikeyStatus struct {
	ApikeyStatus ApikeyStatus
	Valid        bool // Valid is true if ApikeyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApikeyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApikeyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApikeyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApikeyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApikeyStatus), nil
}

type AuditAction string

const (
	AuditActionCreate AuditAction = "create"
	AuditActionUpdate AuditAction = "update"
	AuditActionDelete AuditAction = "delete"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction
	Valid       bool // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type CountryStatus string

const (
	CountryStatusActive   CountryStatus = "active"
	CountryStatusInactive CountryStatus = "inactive"
)

func (e *CountryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CountryStatus(s)
	case string:
		*e = CountryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CountryStatus: %T", src)
	}
	return nil
}

type NullCountryStatus struct {
	CountryStatus CountryStatus
	Valid         bool // Valid is true if CountryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCountryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CountryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CountryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCountryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CountryStatus), nil
}

type SessionStatus string

const (
	SessionStatusActive   SessionStatus = "active"
	SessionStatusInactive SessionStatus = "inactive"
	SessionStatusExpired  SessionStatus = "expired"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus
	Valid         bool // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type UserStatus string

const (
	UserStatusActive   UserStatus = "active"
	UserStatusInactive UserStatus = "inactive"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type UserType string

const (
	UserTypeService UserType = "service"
	UserTypeNormal  UserType = "normal"
)

func (e *UserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserType(s)
	case string:
		*e = UserType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserType: %T", src)
	}
	return nil
}

type NullUserType struct {
	UserType UserType
	Valid    bool // Valid is true if UserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserType) Scan(value interface{}) error {
	if value == nil {
		ns.UserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserType), nil
}

type Apikey struct {
	ID        int32
	ApikeyNo  string
	Key       string
	Status    ApikeyStatus
	Merchant  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Audit struct {
	ID        int32
	Action    AuditAction
	TableName string
	RecordNo  string
	OldValue  sql.NullString
	NewValue  sql.NullString
	AuditNo   string
	CreatedAt sql.NullTime
}

type Country struct {
	ID        int32
	CountryNo string
	Name      string
	Code      string
	Currency  string
	Status    CountryStatus
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Postcode struct {
	ID                 int32
	CountryCode        string
	Postcode           string
	PlaceName          string
	StateRegion        string
	StateRegionCode    string
	CountyProvince     string
	CountyProvinceCode string
	Community          string
	CommunityCode      string
	Latitude           string
	Longtitude         string
	Accuracy           string
	H3id               string
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type Session struct {
	ID        int32
	SessionNo string
	UserNo    string
	Device    string
	Token     string
	Status    SessionStatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID         int32
	UserNo     string
	Email      string
	Phone      string
	Firstname  string
	Lastname   string
	Type       UserType
	Status     UserStatus
	LastActive time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
