// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: postalcode.sql

package repository

import (
	"context"
)

const createPostalCode = `-- name: CreatePostalCode :exec
INSERT INTO postcodes (
    country_code, postcode, place_name, state_region, state_region_code,
    county_province, county_province_code, community, community_code,
    latitude, longtitude, accuracy, h3Id
) VALUES (?,?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePostalCodeParams struct {
	CountryCode        string
	Postcode           string
	PlaceName          string
	StateRegion        string
	StateRegionCode    string
	CountyProvince     string
	CountyProvinceCode string
	Community          string
	CommunityCode      string
	Latitude           string
	Longtitude         string
	Accuracy           string
	H3id               string
}

func (q *Queries) CreatePostalCode(ctx context.Context, arg CreatePostalCodeParams) error {
	_, err := q.db.ExecContext(ctx, createPostalCode,
		arg.CountryCode,
		arg.Postcode,
		arg.PlaceName,
		arg.StateRegion,
		arg.StateRegionCode,
		arg.CountyProvince,
		arg.CountyProvinceCode,
		arg.Community,
		arg.CommunityCode,
		arg.Latitude,
		arg.Longtitude,
		arg.Accuracy,
		arg.H3id,
	)
	return err
}

const deletePostalCode = `-- name: DeletePostalCode :exec
DELETE FROM postcodes
WHERE id = ?
`

func (q *Queries) DeletePostalCode(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePostalCode, id)
	return err
}

const getPostalCode = `-- name: GetPostalCode :one
SELECT id, country_code, postcode, place_name, state_region, state_region_code, county_province, county_province_code, community, community_code, latitude, longtitude, accuracy, h3id, created_at, updated_at FROM postcodes
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPostalCode(ctx context.Context, id int32) (Postcode, error) {
	row := q.db.QueryRowContext(ctx, getPostalCode, id)
	var i Postcode
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.Postcode,
		&i.PlaceName,
		&i.StateRegion,
		&i.StateRegionCode,
		&i.CountyProvince,
		&i.CountyProvinceCode,
		&i.Community,
		&i.CommunityCode,
		&i.Latitude,
		&i.Longtitude,
		&i.Accuracy,
		&i.H3id,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostalCodeByH3Id = `-- name: GetPostalCodeByH3Id :one
SELECT id, country_code, postcode, place_name, state_region, state_region_code, county_province, county_province_code, community, community_code, latitude, longtitude, accuracy, h3id, created_at, updated_at FROM postcodes
WHERE h3Id = ? LIMIT 1
`

func (q *Queries) GetPostalCodeByH3Id(ctx context.Context, h3id string) (Postcode, error) {
	row := q.db.QueryRowContext(ctx, getPostalCodeByH3Id, h3id)
	var i Postcode
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.Postcode,
		&i.PlaceName,
		&i.StateRegion,
		&i.StateRegionCode,
		&i.CountyProvince,
		&i.CountyProvinceCode,
		&i.Community,
		&i.CommunityCode,
		&i.Latitude,
		&i.Longtitude,
		&i.Accuracy,
		&i.H3id,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostalCodes = `-- name: GetPostalCodes :many
SELECT id, country_code, postcode, place_name, state_region, state_region_code, county_province, county_province_code, community, community_code, latitude, longtitude, accuracy, h3id, created_at, updated_at FROM postcodes
ORDER BY place_name
`

func (q *Queries) GetPostalCodes(ctx context.Context) ([]Postcode, error) {
	rows, err := q.db.QueryContext(ctx, getPostalCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Postcode
	for rows.Next() {
		var i Postcode
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.Postcode,
			&i.PlaceName,
			&i.StateRegion,
			&i.StateRegionCode,
			&i.CountyProvince,
			&i.CountyProvinceCode,
			&i.Community,
			&i.CommunityCode,
			&i.Latitude,
			&i.Longtitude,
			&i.Accuracy,
			&i.H3id,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostalCodesByCountry = `-- name: GetPostalCodesByCountry :many
SELECT id, country_code, postcode, place_name, state_region, state_region_code, county_province, county_province_code, community, community_code, latitude, longtitude, accuracy, h3id, created_at, updated_at FROM postcodes
WHERE country_code = ?  ORDER BY place_name
`

func (q *Queries) GetPostalCodesByCountry(ctx context.Context, countryCode string) ([]Postcode, error) {
	rows, err := q.db.QueryContext(ctx, getPostalCodesByCountry, countryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Postcode
	for rows.Next() {
		var i Postcode
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.Postcode,
			&i.PlaceName,
			&i.StateRegion,
			&i.StateRegionCode,
			&i.CountyProvince,
			&i.CountyProvinceCode,
			&i.Community,
			&i.CommunityCode,
			&i.Latitude,
			&i.Longtitude,
			&i.Accuracy,
			&i.H3id,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostalCodesByCountryPaginated = `-- name: GetPostalCodesByCountryPaginated :many
SELECT id, country_code, postcode, place_name, state_region, state_region_code, county_province, county_province_code, community, community_code, latitude, longtitude, accuracy, h3id, created_at, updated_at FROM postcodes
WHERE country_code = ?
ORDER BY place_name
LIMIT ? OFFSET ?
`

type GetPostalCodesByCountryPaginatedParams struct {
	CountryCode string
	Limit       int32
	Offset      int32
}

func (q *Queries) GetPostalCodesByCountryPaginated(ctx context.Context, arg GetPostalCodesByCountryPaginatedParams) ([]Postcode, error) {
	rows, err := q.db.QueryContext(ctx, getPostalCodesByCountryPaginated, arg.CountryCode, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Postcode
	for rows.Next() {
		var i Postcode
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.Postcode,
			&i.PlaceName,
			&i.StateRegion,
			&i.StateRegionCode,
			&i.CountyProvince,
			&i.CountyProvinceCode,
			&i.Community,
			&i.CommunityCode,
			&i.Latitude,
			&i.Longtitude,
			&i.Accuracy,
			&i.H3id,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostalCodesPaginated = `-- name: GetPostalCodesPaginated :many
SELECT id, country_code, postcode, place_name, state_region, state_region_code, county_province, county_province_code, community, community_code, latitude, longtitude, accuracy, h3id, created_at, updated_at FROM postcodes
ORDER BY place_name
LIMIT ? OFFSET ?
`

type GetPostalCodesPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPostalCodesPaginated(ctx context.Context, arg GetPostalCodesPaginatedParams) ([]Postcode, error) {
	rows, err := q.db.QueryContext(ctx, getPostalCodesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Postcode
	for rows.Next() {
		var i Postcode
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.Postcode,
			&i.PlaceName,
			&i.StateRegion,
			&i.StateRegionCode,
			&i.CountyProvince,
			&i.CountyProvinceCode,
			&i.Community,
			&i.CommunityCode,
			&i.Latitude,
			&i.Longtitude,
			&i.Accuracy,
			&i.H3id,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostalCode = `-- name: SearchPostalCode :many
SELECT id, country_code, postcode, place_name, state_region, state_region_code, county_province, county_province_code, community, community_code, latitude, longtitude, accuracy, h3id, created_at, updated_at FROM postcodes
WHERE place_name LIKE ? OR state_region LIKE ? OR county_province LIKE ?
OR community LIKE ? OR h3Id LIKE ?
`

type SearchPostalCodeParams struct {
	PlaceName      string
	StateRegion    string
	CountyProvince string
	Community      string
	H3id           string
}

func (q *Queries) SearchPostalCode(ctx context.Context, arg SearchPostalCodeParams) ([]Postcode, error) {
	rows, err := q.db.QueryContext(ctx, searchPostalCode,
		arg.PlaceName,
		arg.StateRegion,
		arg.CountyProvince,
		arg.Community,
		arg.H3id,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Postcode
	for rows.Next() {
		var i Postcode
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.Postcode,
			&i.PlaceName,
			&i.StateRegion,
			&i.StateRegionCode,
			&i.CountyProvince,
			&i.CountyProvinceCode,
			&i.Community,
			&i.CommunityCode,
			&i.Latitude,
			&i.Longtitude,
			&i.Accuracy,
			&i.H3id,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostalCodePaginated = `-- name: SearchPostalCodePaginated :many
SELECT id, country_code, postcode, place_name, state_region, state_region_code, county_province, county_province_code, community, community_code, latitude, longtitude, accuracy, h3id, created_at, updated_at FROM postcodes
WHERE place_name LIKE ? OR state_region LIKE ? OR county_province LIKE ?
OR community LIKE ? OR h3Id LIKE ?
ORDER BY place_name
LIMIT ? OFFSET ?
`

type SearchPostalCodePaginatedParams struct {
	PlaceName      string
	StateRegion    string
	CountyProvince string
	Community      string
	H3id           string
	Limit          int32
	Offset         int32
}

func (q *Queries) SearchPostalCodePaginated(ctx context.Context, arg SearchPostalCodePaginatedParams) ([]Postcode, error) {
	rows, err := q.db.QueryContext(ctx, searchPostalCodePaginated,
		arg.PlaceName,
		arg.StateRegion,
		arg.CountyProvince,
		arg.Community,
		arg.H3id,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Postcode
	for rows.Next() {
		var i Postcode
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.Postcode,
			&i.PlaceName,
			&i.StateRegion,
			&i.StateRegionCode,
			&i.CountyProvince,
			&i.CountyProvinceCode,
			&i.Community,
			&i.CommunityCode,
			&i.Latitude,
			&i.Longtitude,
			&i.Accuracy,
			&i.H3id,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostalCode = `-- name: UpdatePostalCode :exec
UPDATE postcodes
SET country_code = ?, postcode = ?, place_name = ?, state_region = ?,
    state_region_code = ?, county_province = ?, county_province_code = ?,
    community = ?, community_code = ?, latitude = ?, longtitude = ?,
    accuracy = ?, h3Id = ?
WHERE id = ?
`

type UpdatePostalCodeParams struct {
	CountryCode        string
	Postcode           string
	PlaceName          string
	StateRegion        string
	StateRegionCode    string
	CountyProvince     string
	CountyProvinceCode string
	Community          string
	CommunityCode      string
	Latitude           string
	Longtitude         string
	Accuracy           string
	H3id               string
	ID                 int32
}

func (q *Queries) UpdatePostalCode(ctx context.Context, arg UpdatePostalCodeParams) error {
	_, err := q.db.ExecContext(ctx, updatePostalCode,
		arg.CountryCode,
		arg.Postcode,
		arg.PlaceName,
		arg.StateRegion,
		arg.StateRegionCode,
		arg.CountyProvince,
		arg.CountyProvinceCode,
		arg.Community,
		arg.CommunityCode,
		arg.Latitude,
		arg.Longtitude,
		arg.Accuracy,
		arg.H3id,
		arg.ID,
	)
	return err
}
